<?php

namespace Kivi;

class MyNews extends \CModule
{
    var $MODULE_ID = 'MyNews';
    var $MODULE_NAME = 'Мои тестовые новости';
    var $MODULE_DESCRIPTION = 'Описание на мои тестовые новости';

    public function DoInstall()
    {
        parent::DoInstall(); // TODO: Change the autogenerated stub
    }

    public function DoUninstall()
    {
        parent::DoUninstall(); // TODO: Change the autogenerated stub
    }
}
